### ISSUE TITLE
Failed to start plugin matterbridge-zigbee2mqtt: Error: Only supported EndpointInterface implementation is Endpoint

### ISSUE THREAD

**Issue by tt2g89** [Luligu/matterbridge-zigbee2mqtt#50] opened 2024-08-06 16:00 UTC
Hi,
as soon as I correctly configured the MQTT server connection, matterbridge-zigbee2mqtt seems to load the devices to crash directly afterwards.
Unfortunately I don’t have a clue what I have to do.
Can you support me? Do I have to blacklist some devices types or something because these are not supported yet? Which? In the FAQ it seemed, that there shouldn’t be a problem with any type of device, right?
Thanks in advance for your support.

matterbridge version: 1.4.1
z2m v2.1.9
Log:
info - [17:46:36.634] [PluginManager]: Loading plugin matterbridge-zigbee2mqtt type
info - [17:46:37.894] [Matterbridge zigbee2mqtt plugin]: Initializing platform: matterbridge-zigbee2mqtt v
info - [17:46:37.894] [Matterbridge zigbee2mqtt plugin]: Loaded zigbee2mqtt parameters from /root/.matterbridge/matterbridge-zigbee2mqtt.config.json:
info - [17:46:37.895] [Matterbridge zigbee2mqtt plugin]: Connecting to MQTT broker: mqtt://192.168.0.100:1883
notice - [17:46:37.937] [PluginManager]: Loaded plugin matterbridge-zigbee2mqtt type DynamicPlatform (entrypoint /usr/lib/node_modules/matterbridge-zigbee2mqtt/dist/index.js)
info - [17:46:37.938] [PluginManager]: Starting plugin matterbridge-zigbee2mqtt type DynamicPlatform
info - [17:46:37.938] [Matterbridge zigbee2mqtt plugin]: Starting zigbee2mqtt dynamic platform v2.1.9: Matterbridge is starting
info - [17:46:37.943] [Matterbridge zigbee2mqtt plugin]: MQTT broker at 192.168.0.100:1883 connected
info - [17:46:37.949] [Matterbridge zigbee2mqtt plugin]: zigbee2MQTT is online
info - [17:46:37.951] [Matterbridge zigbee2mqtt plugin]: MQTT broker at 192.168.0.100:1883 subscribed to: zigbee2mqtt/#
info - [17:46:37.954] [Matterbridge zigbee2mqtt plugin]: zigbee2MQTT version 1.39.0 zh version 0.50.1 zhc version 19.62.0
info - [17:46:37.969] [Matterbridge zigbee2mqtt plugin]: zigbee2MQTT sent 42 devices
info - [17:46:37.971] [Matterbridge zigbee2mqtt plugin]: zigbee2MQTT sent 1 groups
info - [17:46:37.975] [Matterbridge zigbee2mqtt plugin]: zigbee2MQTT device Rollos Büro Iris is online
info - [17:46:37.990] [Matterbridge]: The plugin matterbridge-zigbee2mqtt is up to date. Current version: 2.1.9, Latest version: 2.1.9
info - [17:46:39.441] [Matterbridge zigbee2mqtt plugin]: Registering 42 devices
error - [17:46:39.516] [PluginManager]: Failed to start plugin matterbridge-zigbee2mqtt: Error: Only supported EndpointInterface implementation is Endpoint
error - [17:46:39.666] [Matterbridge]: The plugin matterbridge-zigbee2mqtt is in error state.
error - [17:46:39.666] [Matterbridge]: The bridge will not start until the problem is solved to prevent the controllers from deleting all registered devices.
error - [17:46:39.667] [Matterbridge]: If you want to start the bridge disable the plugin in error state and restart.

**Comment by FreAcX** [comment] 2024-08-07 08:29
Got the same error, hope this helps:

- [10:26:32.626] [Matterbridge zigbee2mqtt plugin]: Registering device Spüle ID: 0xa4c1381a9857f735
debug - [10:26:32.626] [Spüle]: Created MatterEntity: Spüle
debug - [10:26:32.626] [Spüle]: Device Spüle endpoint: type: light property: state => deviceType: MA-onofflight cluster: 6 attribute: onOff
debug - [10:26:32.627] [MatterbridgeDevice]: new MatterbridgeDevice with deviceType: 256-MA-onofflight
debug - [10:26:32.628] [Spüle]: new BridgedBaseDevice Spüle
debug - [10:26:32.628] [Spüle]: - with deviceType: 256-MA-onofflight
debug - [10:26:32.628] [Spüle]: - with cluster: 3-Identify
debug - [10:26:32.628] [Spüle]: - with cluster: 4-Groups
debug - [10:26:32.628] [Spüle]: - with cluster: 6-OnOff
debug - [10:26:32.628] [Spüle]: - with cluster: 6-OnOff
debug - [10:26:32.629] [Spüle]: addDeviceType: 19-MA-bridgedNode
debug - [10:26:32.644] [Spüle]: addDeviceType: 17-MA-powerSource
debug - [10:26:32.645] [Spüle]: Device Spüle endpoint: type: light property: brightness => deviceType: MA-dimmablelight cluster: 8 attribute: currentLevel
debug - [10:26:32.645] [Spüle]: addDeviceTypeAndClusterServer
debug - [10:26:32.645] [Spüle]: - with deviceType: 257-MA-dimmablelight
debug - [10:26:32.646] [Spüle]: addDeviceType: 257-MA-dimmablelight
debug - [10:26:32.646] [Spüle]: - with cluster: 3-Identify
debug - [10:26:32.646] [Spüle]: - with cluster: 4-Groups
debug - [10:26:32.646] [Spüle]: - with cluster: 6-OnOff
debug - [10:26:32.646] [Spüle]: - with cluster: 8-LevelControl
debug - [10:26:32.646] [Spüle]: - with cluster: 8-LevelControl
debug - [10:26:32.647] [Spüle]: Device Spüle transition is supported
debug - [10:26:32.647] [Matterbridge]: Adding bridged device Spüle (MA-onofflight) for plugin matterbridge-zigbee2mqtt
error - [10:26:32.648] [PluginManager]: Failed to start plugin matterbridge-zigbee2mqtt: Error: Only supported EndpointInterface implementation is Endpoint
debug - [10:26:33.092] [Matterbridge]: Cleared startMatterInterval interval for Matterbridge for plugin in error state
error - [10:26:33.092] [Matterbridge]: The plugin matterbridge-zigbee2mqtt is in error state.
error - [10:26:33.092] [Matterbridge]: The bridge will not start until the problem is solved to prevent the controllers from deleting all registered devices.
error - [10:26:33.092] [Matterbridge]: If you want to start the bridge disable the plugin in error state and restart.

**Comment by Luligu** [comment] 2024-08-07 21:30
Hi,
I would try to put Spüle in the black list... 
but honestly I also have the doubt that using that character in the name could also create the issue... try also renaming it. 
Then I would like to solve the problem in the plugin to either reject the device or adding it correctly.
Update me as soon as you understand the issue.
In HOME\Matterbridge\matterbridge-zigbee2mqtt there are 3 files starting with bridge, can you send all of them please so I try to understand the issue.
Thanks.

**Comment by tt2g89** [comment] 2024-08-08 07:00
Hi,
unfortunately I didn’t find the log directory so far with my baby on the arm. :) But I’ve enabled debug again and here are again some frontend logs:
Plugins - Enabling plugin: matterbridge-zigbee2mqtt
debug - [08:37:02.765] [Matterbridge]: The frontend sent /api/command/enableplugin/matterbridge-zigbee2mqtt
debug - [08:37:02.765] [Matterbridge]: Received frontend command: enableplugin:matterbridge-zigbee2mqtt
info - [08:37:02.765] [PluginManager]: Enabled plugin matterbridge-zigbee2mqtt
debug - [08:37:02.766] [PluginManager]: Saved 1 plugins to storage
info - [08:37:02.766] [PluginManager]: Loading plugin matterbridge-zigbee2mqtt type DynamicPlatform
debug - [08:37:02.767] [PluginManager]: Importing plugin matterbridge-zigbee2mqtt from file:///usr/lib/node_modules/matterbridge-zigbee2mqtt/dist/index.js
debug - [08:37:02.767] [PluginManager]: Imported plugin matterbridge-zigbee2mqtt from file:///usr/lib/node_modules/matterbridge-zigbee2mqtt/dist/index.js
debug - [08:37:02.770] [PluginManager]: Loaded config file /root/.matterbridge/matterbridge-zigbee2mqtt.config.json for plugin matterbridge-zigbee2mqtt.
debug - [08:37:02.770] [Matterbridge zigbee2mqtt plugin]: MatterbridgeDynamicPlatform loaded
info - [08:37:02.770] [Matterbridge zigbee2mqtt plugin]: Initializing platform: matterbridge-zigbee2mqtt v
info - [08:37:02.770] [Matterbridge zigbee2mqtt plugin]: Loaded zigbee2mqtt parameters from /root/.matterbridge/matterbridge-zigbee2mqtt.config.json:
debug - [08:37:02.771] [Zigbee2MQTT]: Created new instance with host: 192.168.0.100 port: 1883 topic: zigbee2mqtt username: loxberry password: *****
info - [08:37:02.771] [Matterbridge zigbee2mqtt plugin]: Connecting to MQTT broker: mqtt://192.168.0.100:1883
debug - [08:37:02.771] [Zigbee2MQTT]: Starting connection to mqtt://192.168.0.100:1883...
debug - [08:37:02.772] [Matterbridge zigbee2mqtt plugin]: Created zigbee2mqtt dynamic platform
debug - [08:37:02.772] [Zigbee2MQTT]: Data directory /root/Matterbridge/matterbridge-zigbee2mqtt created successfully.
debug - [08:37:02.773] [PluginManager]: Loaded schema file /usr/lib/node_modules/matterbridge-zigbee2mqtt/matterbridge-zigbee2mqtt.schema.json for plugin matterbridge-zigbee2mqtt.
debug - [08:37:02.773] [PluginManager]: Schema file /root/.matterbridge/matterbridge-zigbee2mqtt.schema.json to delete not found.
notice - [08:37:02.773] [PluginManager]: Loaded plugin matterbridge-zigbee2mqtt type DynamicPlatform (entrypoint /usr/lib/node_modules/matterbridge-zigbee2mqtt/dist/index.js)
info - [08:37:02.773] [PluginManager]: Starting plugin matterbridge-zigbee2mqtt type DynamicPlatform
info - [08:37:02.774] [Matterbridge zigbee2mqtt plugin]: Starting zigbee2mqtt dynamic platform v2.1.9: The plugin has been enabled
debug - [08:37:02.774] [Zigbee2MQTT]: Connection established
debug - [08:37:02.774] [Zigbee2MQTT]: Started
info - [08:37:02.774] [Matterbridge zigbee2mqtt plugin]: MQTT broker at 192.168.0.100:1883 connected
debug - [08:37:02.774] [Zigbee2MQTT]: Subscribing topic: zigbee2mqtt/#
info - [08:37:02.776] [Matterbridge zigbee2mqtt plugin]: zigbee2MQTT is online
debug - [08:37:02.776] [Zigbee2MQTT]: Message bridge/state online => true
debug - [08:37:02.776] [Zigbee2MQTT]: Subscribe success on topic: zigbee2mqtt/#
info - [08:37:02.776] [Matterbridge zigbee2mqtt plugin]: MQTT broker at 192.168.0.100:1883 subscribed to: zigbee2mqtt/#
debug - [08:37:02.777] [Zigbee2MQTT]: Message bridge/info availability => false
debug - [08:37:02.777] [Zigbee2MQTT]: Message bridge/info version => 1.39.0
debug - [08:37:02.777] [Zigbee2MQTT]: Message bridge/info permit_join => true timeout => 0
debug - [08:37:02.777] [Zigbee2MQTT]: Message bridge/info advanced.output => json
debug - [08:37:02.777] [Zigbee2MQTT]: Message bridge/info advanced.legacy_api => false
debug - [08:37:02.777] [Zigbee2MQTT]: Message bridge/info advanced.legacy_availability_payload => false
info - [08:37:02.778] [Matterbridge zigbee2mqtt plugin]: zigbee2MQTT version 1.39.0 zh version 0.50.1 zhc version 19.62.0
info - [08:37:02.785] [Matterbridge zigbee2mqtt plugin]: zigbee2MQTT sent 42 devices
debug - [08:37:02.786] [Zigbee2MQTT]: Received 42 devices
info - [08:37:02.786] [Matterbridge zigbee2mqtt plugin]: zigbee2MQTT sent 1 groups
debug - [08:37:02.786] [Zigbee2MQTT]: Received 1 groups
debug - [08:37:02.786] [Zigbee2MQTT]: Message topic: zigbee2mqtt/bridge/definitions
info - [08:37:02.786] [Matterbridge zigbee2mqtt plugin]: zigbee2MQTT device Rollos Büro Iris is online
debug - [08:37:02.787] [Zigbee2MQTT]: Successfully wrote to /root/Matterbridge/matterbridge-zigbee2mqtt/bridge-info.json
debug - [08:37:02.788] [Zigbee2MQTT]: Successfully wrote to /root/Matterbridge/matterbridge-zigbee2mqtt/bridge-groups.json
debug - [08:37:02.788] [Zigbee2MQTT]: Successfully wrote to /root/Matterbridge/matterbridge-zigbee2mqtt/bridge-devices.json
debug - [08:37:03.266] [Matterbridge]: The frontend sent /api/settings
debug - [08:37:03.266] [Matterbridge]: WebSocketServer logger local callback: inactive
debug - [08:37:03.266] [Matterbridge]: WebSocketServer logger global callback: active
debug - [08:37:03.267] [Matterbridge]: The frontend sent /api/plugins
info - [08:37:04.276] [Matterbridge zigbee2mqtt plugin]: Registering 42 devices
debug - [08:37:04.276] [Matterbridge zigbee2mqtt plugin]: Registering device Coordinator ID: 0xb43522fffefc2311
debug - [08:37:04.276] [Coordinator]: Created MatterEntity: Coordinator
debug - [08:37:04.277] [MatterbridgeDevice]: new MatterbridgeDevice with deviceType: 10-MA-doorlock
debug - [08:37:04.278] [Coordinator]: new BridgedBaseDevice Coordinator
debug - [08:37:04.278] [Coordinator]: - with deviceType: 10-MA-doorlock
debug - [08:37:04.278] [Coordinator]: - with cluster: 3-Identify
debug - [08:37:04.278] [Coordinator]: - with cluster: 257-DoorLock
debug - [08:37:04.313] [Coordinator]: addDeviceType: 19-MA-bridgedNode
debug - [08:37:04.337] [Coordinator]: addDeviceType: 17-MA-powerSource
debug - [08:37:04.338] [Matterbridge]: Adding bridged device Coordinator (MA-doorlock) for plugin matterbridge-zigbee2mqtt
error - [08:37:04.338] [PluginManager]: Failed to start plugin matterbridge-zigbee2mqtt: Error: Only supported EndpointInterface implementation is Endpoint
error - [08:37:04.338] [PluginManager]: Plugin matterbridge-zigbee2mqtt not started

**Comment by FreAcX** [comment] 2024-08-08 08:31
> Hi, I would try to put Spüle in the black list... but honestly I also have the doubt that using that character in the name could also create the issue... try also renaming it. Then I would like to solve the problem in the plugin to either reject the device or adding it correctly. Update me as soon as you understand the issue. In HOME\Matterbridge\matterbridge-zigbee2mqtt there are 3 files starting with bridge, can you send all of them please so I try to understand the issue. Thanks.

I have tried the blacklist, but without success. I think these special characters may be the reason, but in Germany it is not possible to live without them. For me, renaming the devices is not possible, as they are then not addressable in Alexa and have to be renamed individually. And this happens after every restart of Matterbridge, as Alexa then changes the names again. 

As a test, I only added the "Couch" device to the whitelist, but without success.

**Comment by Luligu** [comment] 2024-08-08 14:42
Hi,
in the HOME\Matterbridge\matterbridge-zigbee2mqtt from HOME directory on the machine you run matterbridge, there are 3 files starting with bridge, can you send all of them please so I try to understand the issue.

What do you mean with: So 42 devices are filtered out because they are not on the whitelist. Should this not be 78 because only "Couch" is on the whitelist? 
It stops because of the error... I guess.

From the other log I understand you should put the Coordinator in the blackList. But I still need the files to understand and correct the bug.

**Comment by Luligu** [comment] 2024-08-08 15:27
I'm testing a fix to avoid preventing the plugin to load but still need the files from both of you to solve the issue at the origin of it
Thanks

**Comment by FreAcX** [comment] 2024-08-08 17:21
Here are the files:

[bridge-devices.json](https://github.com/user-attachments/files/16551414/bridge-devices.json)
[bridge-info.json](https://github.com/user-attachments/files/16551415/bridge-info.json)
[bridge-groups.json](https://github.com/user-attachments/files/16551416/bridge-groups.json)

**Comment by tt2g89** [comment] 2024-08-08 18:35
Will send you mine aprx. tomorrow.
________________________________
Von: FreAcX ***@***.***>
Gesendet: Thursday, August 8, 2024 7:21:29 PM
An: Luligu/matterbridge-zigbee2mqtt ***@***.***>
Cc: T ***@***.***>; Author ***@***.***>
Betreff: Re: [Luligu/matterbridge-zigbee2mqtt] Failed to start plugin matterbridge-zigbee2mqtt: Error: Only supported EndpointInterface implementation is Endpoint (Issue #50)


Here are the files:

bridge-devices.json<https://github.com/user-attachments/files/16551414/bridge-devices.json>
bridge-info.json<https://github.com/user-attachments/files/16551415/bridge-info.json>
bridge-groups.json<https://github.com/user-attachments/files/16551416/bridge-groups.json>

**Comment by Luligu** [comment] 2024-08-08 20:42
Thanks @FreAcX.
I loaded your devices and there is absolutely nothing wrong with them...
Let see tomorrow when you upgrade to the latest what messages you get...
The fix will prevent to put the plugin in error mode.
Tomorrow send me please a complete log from the console not frontend and with plugin in debug mode.

**Comment by Luligu** [comment] 2024-08-08 21:03
How do you (@tt2g89 @FreAcX) run matterbridge? 
Standalone, service, docker or docker compose?
On what machine?

**Comment by FreAcX** [comment] 2024-08-08 21:08
> Thanks @FreAcX. I loaded your devices and there is absolutely nothing wrong with them... Let see tomorrow when you upgrade to the latest what messages you get... The fix will prevent to put the plugin in error mode. Tomorrow send me please a complete (starting from when you start matterbridge) log from the console not frontend and with plugin in debug mode.

I'm gonna test it tomorrow and will give you feedback

**Comment by FreAcX** [comment] 2024-08-08 21:11
> How do you (@tt2g89 @FreAcX) run matterbridge? Standalone, service, docker or docker compose? On what machine?

LXC via ProxMox, setup by HelperScript from tteck:
https://github.com/tteck/Proxmox/raw/main/ct/matterbridge.sh

**Comment by Luligu** [comment] 2024-08-08 21:22
Hi,
that script does an installation from GitHub... really bad idea in my opinion.
The official latest is on npm with a build made in a different way.
I would not use that way.
Send me please the systemctrl configuration file so at least I can check is created correctly.
We will see tomorrow with a full log debug.

**Comment by Luligu** [comment] 2024-08-09 07:04
## [2.1.10] - 2024-08-09

### Changed

- [package]: Updated dependencies.
- [logger]: Update mqtt to 5.9.1.

### Fixed

- [z2m]: Fixed issue: 'Only supported EndpointInterface implementation is Endpoint'.

<a href="https://www.buymeacoffee.com/luligugithub">
  <img src="./yellow-button.png" alt="Buy me a coffee" width="120">
</a>

**Comment by FreAcX** [comment] 2024-08-09 07:53
Thanks for the commit.
I've tested with the HomeAssistant MatterBridge Addon and it's working like a charm.
To be honest, this was also my planned application, but I didn't want to test it on my production system. WAF, you know.

On my LXC implementation it's still not working. Your new version allows MatterBridge to start, but it's not registering the device:

error - [09:49:20.479] [Matterbridge zigbee2mqtt plugin]: Error registering device Couch ID: 0x0017880102235185: Error: Only supported EndpointInterface implementation is Endpoint

I will setup a Debian LXC and install MatterBridge the recommended way. 
How do I get the full log debug? You say not from the frontend, but I don't see any other Matterbridge logs. Is there a log file?

**Comment by FreAcX** [comment] 2024-08-09 07:57
systemctl-configuration from LXC:
```
root@matterbridge:~# systemctl cat matterbridge.service
# /etc/systemd/system/matterbridge.service
[Unit]
Description=matterbridge
After=network-online.target

[Service]
Type=simple
ExecStart=/usr/bin/npm run start:bridge
WorkingDirectory=/opt/matterbridge
StandardOutput=inherit
StandardError=inherit
Restart=always
RestartSec=10s
TimeoutStopSec=30s
User=root
Environment=PATH=/usr/bin:/usr/local/bin:/opt/matterbridge/bin
Environment=NODE_ENV=production

[Install]
WantedBy=multi-user.target
```

**Comment by tt2g89** [comment] 2024-08-09 08:12
> > How do you (@tt2g89 @FreAcX) run matterbridge? Standalone, service, docker or docker compose? On what machine?
> 
> LXC via ProxMox, setup by HelperScript from tteck: https://github.com/tteck/Proxmox/raw/main/ct/matterbridge.sh

Same on May l my side LXC via Proxmix helper script.
Will also try the HA addon.
@Luligu  could you please add the log paths to your readme? Could be also helpful for the community. 🙂
Thanks for your work! I’m looking forward to test it later.
@FreAcX  thanks to you as well for giving your data to @Luligu!

**Comment by FreAcX** [comment] 2024-08-09 08:27
Installed on a Debian LXC, everything works just as well. 
So it really seems to be the implementation of the tteck helperscript. 
I think then the issue can be closed as it is not a problem with your implementation.

**Closed** 2024-08-09 09:37 UTC

**Comment by Luligu** [comment] 2024-08-09 09:40
> systemctl configuration from LXC:
> 
> ```
> root@matterbridge:~# systemctl cat matterbridge.service
> # /etc/systemd/system/matterbridge.service
> [Unit]
> Description=matterbridge
> After=network-online.target
> 
> [Service]
> Type=simple
> ExecStart=/usr/bin/npm run start:bridge
> WorkingDirectory=/opt/matterbridge
> StandardOutput=inherit
> StandardError=inherit
> Restart=always
> RestartSec=10s
> TimeoutStopSec=30s
> User=root
> Environment=PATH=/usr/bin:/usr/local/bin:/opt/matterbridge/bin
> Environment=NODE_ENV=production
> 
> [Install]
> WantedBy=multi-user.target
> ```

This is absolutely wrong!!! Someone should tell them that they release a wrong stuff

**Comment by Luligu** [comment] 2024-08-09 09:41
> Installed on a Debian LXC, everything works just as well. So it really seems to be the implementation of the tteck helperscript. I think then the issue can be closed as it is not a problem with your implementation.

It is absolutely wrong!

**Comment by Luligu** [comment] 2024-08-09 09:42
Can you open an issue on that stuff, they have either to remove the script or adjust it following the guidelines...

**Comment by Luligu** [comment] 2024-08-09 09:46
> > > How do you (@tt2g89 @FreAcX) run matterbridge? Standalone, service, docker or docker compose? On what machine?
> > 
> > 
> > LXC via ProxMox, setup by HelperScript from tteck: https://github.com/tteck/Proxmox/raw/main/ct/matterbridge.sh
> 
> Same on May l my side LXC via Proxmix helper script. Will also try the HA addon. @Luligu could you please add the log paths to your readme? Could be also helpful for the community. 🙂 Thanks for your work! I’m looking forward to test it later. @FreAcX thanks to you as well for giving your data to @Luligu!

In the readme there are the instructions to get the log with systemctrl and doker. If you run it standalone just copy paste from the terminal.

https://github.com/Luligu/matterbridge?tab=readme-ov-file#view-the-log-of-matterbridge-in-real-time-this-will-show-the-log-with-colors

and 

https://github.com/Luligu/matterbridge?tab=readme-ov-file#shows-the-logs-real-time-tail

**Comment by tt2g89** [comment] 2024-08-09 09:55
> > > > How do you (@tt2g89 @FreAcX) run matterbridge? Standalone, service, docker or docker compose? On what machine?
> > > 
> > > 
> > > LXC via ProxMox, setup by HelperScript from tteck: https://github.com/tteck/Proxmox/raw/main/ct/matterbridge.sh
> > 
> > 
> > Same on May l my side LXC via Proxmix helper script. Will also try the HA addon. @Luligu could you please add the log paths to your readme? Could be also helpful for the community. 🙂 Thanks for your work! I’m looking forward to test it later. @FreAcX thanks to you as well for giving your data to @Luligu!
> 
> In the readme there are the instructions to get the log with systemctrl and doker. If you run it standalone just copy paste from the terminal.
> 
> https://github.com/Luligu/matterbridge?tab=readme-ov-file#view-the-log-of-matterbridge-in-real-time-this-will-show-the-log-with-colors
> 
> and
> 
> https://github.com/Luligu/matterbridge?tab=readme-ov-file#shows-the-logs-real-time-tail

yup, found it. Will open an issue and refer to this issue.
Thx

**Comment by tt2g89** [comment] 2024-08-09 10:43
https://github.com/tteck/Proxmox/discussions/3498
